// Generated by IntelliJ-IDEA Scala plugin.
// Add settings when starting sbt from IDEA.
// Manual changes to this file will be lost.
if (java.lang.System.getProperty("idea.runid", "false") == "7.0.0+61-051fb9ba") scala.collection.Seq(
addSbtPlugin("org.jetbrains" % "sbt-structure-extractor" % "7.0.0+61-051fb9ba"),
addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "1.2+7-625c26bc")
) else scala.collection.Seq.empty